plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/admi/.openclaw/workspace/businesses/workflow-crm-automation/deploy"
publishOrigin = "default"
base = "/home/admi/.openclaw/workspace/businesses/workflow-crm-automation/deploy"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]